{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 7.4,
              "attackVector": "NETWORK",
              "baseSeverity": "HIGH",
              "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "HIGH",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "HIGH"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-0397",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-06-20T15:52:27.499743Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:python_software_foundation:cpython:*:*:*:*:*:*:*:*"
            ],
            "vendor": "python_software_foundation",
            "product": "cpython",
            "versions": [
              {
                "status": "affected",
                "version": "3.13.0a1",
                "lessThan": "3.13.0a5",
                "versionType": "python"
              },
              {
                "status": "affected",
                "version": "3.12.0",
                "lessThan": "3.12.3",
                "versionType": "python"
              },
              {
                "status": "affected",
                "version": "3.11.0",
                "lessThan": "3.11.9",
                "versionType": "python"
              },
              {
                "status": "affected",
                "version": "0",
                "lessThan": "3.10.14",
                "versionType": "python"
              }
            ],
            "defaultStatus": "unaffected"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-362",
                "description": "CWE-362 Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-06-20T16:06:44.461Z"
        }
      }
    ],
    "cna": {
      "title": "Memory race condition in ssl.SSLContext certificate store methods",
      "source": {
        "discovery": "UNKNOWN"
      },
      "affected": [
        {
          "repo": "https://github.com/python/cpython",
          "vendor": "Python Software Foundation",
          "product": "CPython",
          "versions": [
            {
              "status": "affected",
              "version": "3.13.0a1",
              "lessThan": "3.13.0a5",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "3.12.0",
              "lessThan": "3.12.3",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "3.11.0",
              "lessThan": "3.11.9",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "0",
              "lessThan": "3.10.14",
              "versionType": "python"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "references": [
        {
          "url": "https://github.com/python/cpython/issues/114572",
          "tags": [
            "issue-tracking"
          ]
        },
        {
          "url": "https://github.com/python/cpython/pull/114573",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/",
          "tags": [
            "vendor-advisory"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab",
          "tags": [
            "patch"
          ]
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2024/06/17/2"
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.2.0"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "A defect was discovered in the Python \u201cssl\u201d module where there is a memory\nrace condition with the ssl.SSLContext methods \u201ccert_store_stats()\u201d and\n\u201cget_ca_certs()\u201d. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "A defect was discovered in the Python \u201cssl\u201d module where there is a memory\nrace condition with the ssl.SSLContext methods \u201ccert_store_stats()\u201d and\n\u201cget_ca_certs()\u201d. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
              "base64": false
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "28c92f92-d60d-412d-b760-e73465c3df22",
        "shortName": "PSF",
        "dateUpdated": "2024-06-17T15:11:16.322Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-0397",
    "state": "PUBLISHED",
    "dateUpdated": "2024-06-20T16:08:46.179Z",
    "dateReserved": "2024-01-10T14:05:31.635Z",
    "assignerOrgId": "28c92f92-d60d-412d-b760-e73465c3df22",
    "datePublished": "2024-06-17T15:09:40.896Z",
    "assignerShortName": "PSF"
  },
  "dataVersion": "5.1"
}