{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.0",
  "cveMetadata": {
    "cveId": "CVE-2024-32879",
    "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
    "state": "PUBLISHED",
    "assignerShortName": "GitHub_M",
    "dateReserved": "2024-04-19T14:07:11.230Z",
    "datePublished": "2024-04-24T19:42:14.642Z",
    "dateUpdated": "2024-04-24T19:42:14.642Z"
  },
  "containers": {
    "cna": {
      "title": "social-auth-app-django Improper Handling of Case Sensitivity vulnerability",
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-178",
              "lang": "en",
              "description": "CWE-178: Improper Handling of Case Sensitivity",
              "type": "CWE"
            }
          ]
        },
        {
          "descriptions": [
            {
              "cweId": "CWE-303",
              "lang": "en",
              "description": "CWE-303: Incorrect Implementation of Authentication Algorithm",
              "type": "CWE"
            }
          ]
        }
      ],
      "metrics": [
        {
          "cvssV3_1": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "NONE",
            "baseScore": 4.9,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "LOW",
            "integrityImpact": "LOW",
            "privilegesRequired": "LOW",
            "scope": "CHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:C/C:L/I:L/A:N",
            "version": "3.1"
          }
        }
      ],
      "references": [
        {
          "name": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3",
          "tags": [
            "x_refsource_CONFIRM"
          ],
          "url": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-2gr8-3wc7-xhj3"
        },
        {
          "name": "https://github.com/python-social-auth/social-app-django/pull/566",
          "tags": [
            "x_refsource_MISC"
          ],
          "url": "https://github.com/python-social-auth/social-app-django/pull/566"
        },
        {
          "name": "https://github.com/python-social-auth/social-app-django/commit/31c3e0c7edb187004d8abbde7e9c4f7ef9098138",
          "tags": [
            "x_refsource_MISC"
          ],
          "url": "https://github.com/python-social-auth/social-app-django/commit/31c3e0c7edb187004d8abbde7e9c4f7ef9098138"
        }
      ],
      "affected": [
        {
          "vendor": "python-social-auth",
          "product": "social-app-django",
          "versions": [
            {
              "version": "< 5.4.1",
              "status": "affected"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "shortName": "GitHub_M",
        "dateUpdated": "2024-04-24T19:42:14.642Z"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field."
        }
      ],
      "source": {
        "advisory": "GHSA-2gr8-3wc7-xhj3",
        "discovery": "UNKNOWN"
      }
    },
    "adp": [
      {
        "title": "CISA ADP Pilot - Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-32879",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-04-29T19:27:52.308869Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:python-social-auth:social-app-django:*:*:*:*:*:*:*:*"
            ],
            "vendor": "python-social-auth",
            "product": "social-app-django",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "5.4.1",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "shortName": "CISA-ADP",
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "dateUpdated": "2024-04-29T19:27:46.692Z"
        }
      }
    ]
  }
}